packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^24.5.2
  eslint: ^9.36.0
  prettier: ^3.6.2
  tsdown: ^0.15.3
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
