packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^24.3.0
  eslint: ^9.34.0
  prettier: ^3.6.2
  tsdown: ^0.14.1
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
