packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^24.2.0
  eslint: ^9.33.0
  prettier: ^3.6.2
  tsdown: ^0.13.3
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
