packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': 24.12.2
  eslint: 10.2.1
  prettier: 3.8.3
  tsdown: 0.21.7
  typescript: 6.0.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
