packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^24.0.3
  prettier: ^3.6.0
  tsdown: ^0.12.8
  typescript: ^5.8.3
  eslint: ^9.29.0

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
