packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^24.0.12
  prettier: ^3.6.2
  tsdown: ^0.12.9
  typescript: ^5.8.3
  eslint: ^9.30.1

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
