packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': 24.10.10
  eslint: 9.39.2
  prettier: 3.8.1
  tsdown: 0.20.0
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
