packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': 24.10.3
  eslint: 9.39.2
  prettier: 3.7.4
  tsdown: 0.17.3
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
