packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': 24.7.1
  eslint: 9.37.0
  prettier: 3.6.2
  tsdown: 0.15.6
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
