packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': 24.10.0
  eslint: 9.39.1
  prettier: 3.6.2
  tsdown: 0.16.3
  typescript: 5.9.3

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
