packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@ianvs/prettier-plugin-sort-imports': 4.7.1
  '@types/node': 25.9.1
  oxfmt: 0.50.0
  oxlint: ^1.65.0
  oxlint-tsgolint: ^0.23.0
  prettier: 3.8.3
  prettier-plugin-packagejson: 3.0.2
  prettier-plugin-tailwindcss: ^0.8.0
  tsdown: 0.22.2
  turbo: 2.9.14
  typescript: 6.0.3

catalogMode: prefer

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true
verifyDepsBeforeRun: warn

publicHoistPattern:
  - '*eslint*'
  - '*prettier*'
  - '*vitest*'

savePrefix: ''

allowBuilds:
  '@swc/core': true
  core-js: true
  unrs-resolver: true
