packages:
  - packages/*
  - '!**/test/**'
  - '!**/__test__/**'

catalog:
  '@types/node': ^24.3.1
  eslint: ^9.35.0
  prettier: ^3.6.2
  tsdown: ^0.14.2
  typescript: ^5.9.2

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - unrs-resolver
