name: 🔥 Pull requests

on:
  pull_request:
  check_run:
    types:
      - requested_action

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  statuses: write

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  danger:
    name: 🔥 Danger
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - uses: ./.github/common-actions/install

      - name: 🔨 Build
        run: pnpm build

      - name: 🔥 Run Danger
        run: npx danger ci --use-github-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: danger-artifacts
          path: ${{ env.ARTIFACT_DIR }}


  tests:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v6

      - name: 📥 Setup
        uses: ./.github/common-actions/install

      - name: 🧪 Run tests
        run: pnpm test

  eslint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v6

      - name: 📥 Setup
        uses: ./.github/common-actions/install

      - name: 🔬 Lint
        run: pnpm lint

  types:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v6

      - name: 📥 Setup
        uses: ./.github/common-actions/install

      - name: 🔎 Type check
        run: pnpm typecheck

  oxfmt:
    name: 📝 Oxfmt
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v6

      - name: 📥 Setup
        uses: ./.github/common-actions/install

      - name: 📝 Run oxfmt
        run: pnpm format

  continuous-release:
    name: 🦋 Continuous Release
    if: github.repository == 'rajzik/configs'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout branch
        uses: actions/checkout@v6

      - name: 📥 Setup
        uses: ./.github/common-actions/install

      - name: 🚀 PR Release
        run: pnpx pkg-pr-new publish --pnpm './packages/*'