name: Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - canary

env:
  CI: 1
  ARTIFACT_DIR: ./artifacts

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Create artifacts directory
        run: mkdir -p ${{ env.ARTIFACT_DIR }}

      - uses: ./.github/common-actions/install

      - name: Tests
        run: pnpm test:all

      - name: Create Release Pull Request or Publish to NPM
        # Run only if the build is successful
        if: success()
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          title: "ci(changesets): :package: version packages"
          commit: "ci(changesets): version packages"
          setupGitUser: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
